// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import AlertsController from "./alerts_controller";
application.register("alerts", AlertsController);

import TiptapController from "./tiptap_controller";
application.register("tiptap", TiptapController);

import HighlightController from "./highlight_controller";
application.register("highlight", HighlightController);
